//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerLogin
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerLogin.IWsLogin")]
    public interface IWsLogin
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#CheckModuleStation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.CheckModuleStationResponse CheckModuleStation(ServerLogin.CheckModuleStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#CheckModuleStation", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.CheckModuleStationResponse> CheckModuleStationAsync(ServerLogin.CheckModuleStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UserLoginResponse UserLogin(ServerLogin.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UserLoginResponse> UserLoginAsync(ServerLogin.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UserLogin2Response UserLogin2(ServerLogin.UserLogin2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UserLogin2Response> UserLogin2Async(ServerLogin.UserLogin2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UserLogin3Response UserLogin3(ServerLogin.UserLogin3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin3", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UserLogin3Response> UserLogin3Async(ServerLogin.UserLogin3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UserLogin4Response UserLogin4(ServerLogin.UserLogin4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogin4", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UserLogin4Response> UserLogin4Async(ServerLogin.UserLogin4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UserLogoutResponse UserLogout(ServerLogin.UserLogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogout", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UserLogoutResponse> UserLogoutAsync(ServerLogin.UserLogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogoutForGateKeeper", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UserLogoutForGateKeeperResponse UserLogoutForGateKeeper(ServerLogin.UserLogoutForGateKeeperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UserLogoutForGateKeeper", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UserLogoutForGateKeeperResponse> UserLogoutForGateKeeperAsync(ServerLogin.UserLogoutForGateKeeperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#DisableUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.DisableUserResponse DisableUser(ServerLogin.DisableUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#DisableUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.DisableUserResponse> DisableUserAsync(ServerLogin.DisableUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#FindSessionItemDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.FindSessionItemDBResponse FindSessionItemDB(ServerLogin.FindSessionItemDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#FindSessionItemDB", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.FindSessionItemDBResponse> FindSessionItemDBAsync(ServerLogin.FindSessionItemDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#DeleteSessionData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.DeleteSessionDataResponse DeleteSessionData(ServerLogin.DeleteSessionDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#DeleteSessionData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.DeleteSessionDataResponse> DeleteSessionDataAsync(ServerLogin.DeleteSessionDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#CreateUserLogData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.CreateUserLogDataResponse CreateUserLogData(ServerLogin.CreateUserLogDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#CreateUserLogData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.CreateUserLogDataResponse> CreateUserLogDataAsync(ServerLogin.CreateUserLogDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#SynchUserLogData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.SynchUserLogDataResponse SynchUserLogData(ServerLogin.SynchUserLogDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#SynchUserLogData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.SynchUserLogDataResponse> SynchUserLogDataAsync(ServerLogin.SynchUserLogDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#ChangeUserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.ChangeUserLoginResponse ChangeUserLogin(ServerLogin.ChangeUserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#ChangeUserLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.ChangeUserLoginResponse> ChangeUserLoginAsync(ServerLogin.ChangeUserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#Check", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.CheckResponse Check(ServerLogin.CheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#Check", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.CheckResponse> CheckAsync(ServerLogin.CheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#CheckSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.CheckSessionResponse CheckSession(ServerLogin.CheckSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#CheckSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.CheckSessionResponse> CheckSessionAsync(ServerLogin.CheckSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#SetLoadTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.SetLoadTicketResponse SetLoadTicket(ServerLogin.SetLoadTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#SetLoadTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.SetLoadTicketResponse> SetLoadTicketAsync(ServerLogin.SetLoadTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UpdateWorkstationVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UpdateWorkstationVersionResponse UpdateWorkstationVersion(ServerLogin.UpdateWorkstationVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UpdateWorkstationVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UpdateWorkstationVersionResponse> UpdateWorkstationVersionAsync(ServerLogin.UpdateWorkstationVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#RFID_CheckAntenna", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.RFID_CheckAntennaResponse RFID_CheckAntenna(ServerLogin.RFID_CheckAntennaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#RFID_CheckAntenna", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.RFID_CheckAntennaResponse> RFID_CheckAntennaAsync(ServerLogin.RFID_CheckAntennaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#RFID_CheckLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.RFID_CheckLoginResponse RFID_CheckLogin(ServerLogin.RFID_CheckLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#RFID_CheckLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.RFID_CheckLoginResponse> RFID_CheckLoginAsync(ServerLogin.RFID_CheckLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#ReCreateSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.ReCreateSessionResponse ReCreateSession(ServerLogin.ReCreateSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#ReCreateSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.ReCreateSessionResponse> ReCreateSessionAsync(ServerLogin.ReCreateSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#IsDBCompatible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.IsDBCompatibleResponse IsDBCompatible(ServerLogin.IsDBCompatibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#IsDBCompatible", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.IsDBCompatibleResponse> IsDBCompatibleAsync(ServerLogin.IsDBCompatibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#GetWorkstationDeviceIdFromFamilyType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.GetWorkstationDeviceIdFromFamilyTypeResponse GetWorkstationDeviceIdFromFamilyType(ServerLogin.GetWorkstationDeviceIdFromFamilyTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#GetWorkstationDeviceIdFromFamilyType", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.GetWorkstationDeviceIdFromFamilyTypeResponse> GetWorkstationDeviceIdFromFamilyTypeAsync(ServerLogin.GetWorkstationDeviceIdFromFamilyTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#ValidateChangeWorkstation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.ValidateChangeWorkstationResponse ValidateChangeWorkstation(ServerLogin.ValidateChangeWorkstationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#ValidateChangeWorkstation", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.ValidateChangeWorkstationResponse> ValidateChangeWorkstationAsync(ServerLogin.ValidateChangeWorkstationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#IsduplicatedExtAuthCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.IsduplicatedExtAuthCodeResponse IsduplicatedExtAuthCode(ServerLogin.IsduplicatedExtAuthCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#IsduplicatedExtAuthCode", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.IsduplicatedExtAuthCodeResponse> IsduplicatedExtAuthCodeAsync(ServerLogin.IsduplicatedExtAuthCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UpdateWSPath", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ServerLogin.UpdateWSPathResponse UpdateWSPath(ServerLogin.UpdateWSPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WsLoginIntf-IWsLogin#UpdateWSPath", ReplyAction="*")]
        System.Threading.Tasks.Task<ServerLogin.UpdateWSPathResponse> UpdateWSPathAsync(ServerLogin.UpdateWSPathRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckModuleStation", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CheckModuleStationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string aLoginInfo;
        
        public CheckModuleStationRequest()
        {
        }
        
        public CheckModuleStationRequest(string aLoginInfo)
        {
            this.aLoginInfo = aLoginInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckModuleStationResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CheckModuleStationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CheckModuleStationResponse()
        {
        }
        
        public CheckModuleStationResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:uConstCore")]
    public enum TAuthenticationType
    {
        
        /// <remarks/>
        atOverview,
        
        /// <remarks/>
        atWindows,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AWorkstationAK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string AUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string APassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string AClientMACAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public ServerLogin.TAuthenticationType AuthenticationType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string ANewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool AOfflineMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string AOfflinePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string ABosSwVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string ALocalIPAddress;
        
        public UserLoginRequest()
        {
        }
        
        public UserLoginRequest(string AWorkstationAK, string AUserName, string APassword, string AClientMACAddress, ServerLogin.TAuthenticationType AuthenticationType, string ANewPassword, bool AOfflineMode, string AOfflinePassword, string ABosSwVersion, string ALocalIPAddress)
        {
            this.AWorkstationAK = AWorkstationAK;
            this.AUserName = AUserName;
            this.APassword = APassword;
            this.AClientMACAddress = AClientMACAddress;
            this.AuthenticationType = AuthenticationType;
            this.ANewPassword = ANewPassword;
            this.AOfflineMode = AOfflineMode;
            this.AOfflinePassword = AOfflinePassword;
            this.ABosSwVersion = ABosSwVersion;
            this.ALocalIPAddress = ALocalIPAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLoginResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UserLoginResponse()
        {
        }
        
        public UserLoginResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin2", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogin2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AWorkstationAK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string AUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string APassword;
        
        public UserLogin2Request()
        {
        }
        
        public UserLogin2Request(string AWorkstationAK, string AUserName, string APassword)
        {
            this.AWorkstationAK = AWorkstationAK;
            this.AUserName = AUserName;
            this.APassword = APassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin2Response", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogin2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UserLogin2Response()
        {
        }
        
        public UserLogin2Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin3", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogin3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AWorkstationAK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string AUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string AExtAuthCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public uint ACRC;
        
        public UserLogin3Request()
        {
        }
        
        public UserLogin3Request(string AWorkstationAK, string AUserName, string AExtAuthCode, uint ACRC)
        {
            this.AWorkstationAK = AWorkstationAK;
            this.AUserName = AUserName;
            this.AExtAuthCode = AExtAuthCode;
            this.ACRC = ACRC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin3Response", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogin3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UserLogin3Response()
        {
        }
        
        public UserLogin3Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin4", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogin4Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AWorkstationAK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string AUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string APassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string AClientMACAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public ServerLogin.TAuthenticationType AuthenticationType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int AUserGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool AOfflineMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string AOfflinePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string ABosSwVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string ALocalIPAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string AExtAuthCode;
        
        public UserLogin4Request()
        {
        }
        
        public UserLogin4Request(string AWorkstationAK, string AUserName, string APassword, string AClientMACAddress, ServerLogin.TAuthenticationType AuthenticationType, int AUserGroupId, bool AOfflineMode, string AOfflinePassword, string ABosSwVersion, string ALocalIPAddress, string AExtAuthCode)
        {
            this.AWorkstationAK = AWorkstationAK;
            this.AUserName = AUserName;
            this.APassword = APassword;
            this.AClientMACAddress = AClientMACAddress;
            this.AuthenticationType = AuthenticationType;
            this.AUserGroupId = AUserGroupId;
            this.AOfflineMode = AOfflineMode;
            this.AOfflinePassword = AOfflinePassword;
            this.ABosSwVersion = ABosSwVersion;
            this.ALocalIPAddress = ALocalIPAddress;
            this.AExtAuthCode = AExtAuthCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin4Response", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogin4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UserLogin4Response()
        {
        }
        
        public UserLogin4Response(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogout", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogoutRequest
    {
        
        public UserLogoutRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogoutResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogoutResponse
    {
        
        public UserLogoutResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogoutForGateKeeper", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogoutForGateKeeperRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        public UserLogoutForGateKeeperRequest()
        {
        }
        
        public UserLogoutForGateKeeperRequest(string SessionId)
        {
            this.SessionId = SessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogoutForGateKeeperResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UserLogoutForGateKeeperResponse
    {
        
        public UserLogoutForGateKeeperResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisableUser", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class DisableUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AUserID;
        
        public DisableUserRequest()
        {
        }
        
        public DisableUserRequest(int AUserID)
        {
            this.AUserID = AUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisableUserResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class DisableUserResponse
    {
        
        public DisableUserResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindSessionItemDB", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class FindSessionItemDBRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ASessionID;
        
        public FindSessionItemDBRequest()
        {
        }
        
        public FindSessionItemDBRequest(string ASessionID)
        {
            this.ASessionID = ASessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindSessionItemDBResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class FindSessionItemDBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public FindSessionItemDBResponse()
        {
        }
        
        public FindSessionItemDBResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSessionData", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class DeleteSessionDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ACryptedSessionId;
        
        public DeleteSessionDataRequest()
        {
        }
        
        public DeleteSessionDataRequest(string ACryptedSessionId)
        {
            this.ACryptedSessionId = ACryptedSessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSessionDataResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class DeleteSessionDataResponse
    {
        
        public DeleteSessionDataResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserLogData", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CreateUserLogDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ALogType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int AEntityTable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int AEntityId;
        
        public CreateUserLogDataRequest()
        {
        }
        
        public CreateUserLogDataRequest(int ALogType, int AEntityTable, int AEntityId)
        {
            this.ALogType = ALogType;
            this.AEntityTable = AEntityTable;
            this.AEntityId = AEntityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserLogDataResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CreateUserLogDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public CreateUserLogDataResponse()
        {
        }
        
        public CreateUserLogDataResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SynchUserLogData", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class SynchUserLogDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object ALogType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public object AUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public object AWksId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public object AUserGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public object ALogDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public object AIPAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public object AEntityTable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public object AEntityId;
        
        public SynchUserLogDataRequest()
        {
        }
        
        public SynchUserLogDataRequest(object ALogType, object AUserId, object AWksId, object AUserGroupId, object ALogDate, object AIPAddress, object AEntityTable, object AEntityId)
        {
            this.ALogType = ALogType;
            this.AUserId = AUserId;
            this.AWksId = AWksId;
            this.AUserGroupId = AUserGroupId;
            this.ALogDate = ALogDate;
            this.AIPAddress = AIPAddress;
            this.AEntityTable = AEntityTable;
            this.AEntityId = AEntityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SynchUserLogDataResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class SynchUserLogDataResponse
    {
        
        public SynchUserLogDataResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeUserLogin", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class ChangeUserLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AWorkstationAK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string AUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string APassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public ServerLogin.TAuthenticationType AuthenticationType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string AExtAuthCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string ARightCheck;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int AUserGroupId;
        
        public ChangeUserLoginRequest()
        {
        }
        
        public ChangeUserLoginRequest(string AWorkstationAK, string AUserName, string APassword, ServerLogin.TAuthenticationType AuthenticationType, string AExtAuthCode, string ARightCheck, int AUserGroupId)
        {
            this.AWorkstationAK = AWorkstationAK;
            this.AUserName = AUserName;
            this.APassword = APassword;
            this.AuthenticationType = AuthenticationType;
            this.AExtAuthCode = AExtAuthCode;
            this.ARightCheck = ARightCheck;
            this.AUserGroupId = AUserGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeUserLoginResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class ChangeUserLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ChangeUserLoginResponse()
        {
        }
        
        public ChangeUserLoginResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Check", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CheckRequest
    {
        
        public CheckRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CheckResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public CheckResponse()
        {
        }
        
        public CheckResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckSession", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CheckSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string aSession;
        
        public CheckSessionRequest()
        {
        }
        
        public CheckSessionRequest(string aSession)
        {
            this.aSession = aSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckSessionResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class CheckSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public CheckSessionResponse()
        {
        }
        
        public CheckSessionResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetLoadTicket", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class SetLoadTicketRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AWorkStationId;
        
        public SetLoadTicketRequest()
        {
        }
        
        public SetLoadTicketRequest(int AWorkStationId)
        {
            this.AWorkStationId = AWorkStationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetLoadTicketResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class SetLoadTicketResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public SetLoadTicketResponse()
        {
        }
        
        public SetLoadTicketResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWorkstationVersion", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UpdateWorkstationVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AWorkStationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string aVersion;
        
        public UpdateWorkstationVersionRequest()
        {
        }
        
        public UpdateWorkstationVersionRequest(int AWorkStationId, string aVersion)
        {
            this.AWorkStationId = AWorkStationId;
            this.aVersion = aVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWorkstationVersionResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UpdateWorkstationVersionResponse
    {
        
        public UpdateWorkstationVersionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RFID_CheckAntenna", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class RFID_CheckAntennaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AWorkstationId;
        
        public RFID_CheckAntennaRequest()
        {
        }
        
        public RFID_CheckAntennaRequest(int AWorkstationId)
        {
            this.AWorkstationId = AWorkstationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RFID_CheckAntennaResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class RFID_CheckAntennaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public RFID_CheckAntennaResponse()
        {
        }
        
        public RFID_CheckAntennaResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RFID_CheckLogin", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class RFID_CheckLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AWorkstationId;
        
        public RFID_CheckLoginRequest()
        {
        }
        
        public RFID_CheckLoginRequest(int AWorkstationId)
        {
            this.AWorkstationId = AWorkstationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RFID_CheckLoginResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class RFID_CheckLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public RFID_CheckLoginResponse()
        {
        }
        
        public RFID_CheckLoginResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReCreateSession", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class ReCreateSessionRequest
    {
        
        public ReCreateSessionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReCreateSessionResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class ReCreateSessionResponse
    {
        
        public ReCreateSessionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsDBCompatible", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class IsDBCompatibleRequest
    {
        
        public IsDBCompatibleRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsDBCompatibleResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class IsDBCompatibleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public IsDBCompatibleResponse()
        {
        }
        
        public IsDBCompatibleResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkstationDeviceIdFromFamilyType", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class GetWorkstationDeviceIdFromFamilyTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AWorkstationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int AFamiltyType;
        
        public GetWorkstationDeviceIdFromFamilyTypeRequest()
        {
        }
        
        public GetWorkstationDeviceIdFromFamilyTypeRequest(int AWorkstationId, int AFamiltyType)
        {
            this.AWorkstationId = AWorkstationId;
            this.AFamiltyType = AFamiltyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkstationDeviceIdFromFamilyTypeResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class GetWorkstationDeviceIdFromFamilyTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public GetWorkstationDeviceIdFromFamilyTypeResponse()
        {
        }
        
        public GetWorkstationDeviceIdFromFamilyTypeResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateChangeWorkstation", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class ValidateChangeWorkstationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int AWorkstationId;
        
        public ValidateChangeWorkstationRequest()
        {
        }
        
        public ValidateChangeWorkstationRequest(int AUserId, int AWorkstationId)
        {
            this.AUserId = AUserId;
            this.AWorkstationId = AWorkstationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateChangeWorkstationResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class ValidateChangeWorkstationResponse
    {
        
        public ValidateChangeWorkstationResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsduplicatedExtAuthCode", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class IsduplicatedExtAuthCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string AUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string AExtAuthCode;
        
        public IsduplicatedExtAuthCodeRequest()
        {
        }
        
        public IsduplicatedExtAuthCodeRequest(string AUserId, string AExtAuthCode)
        {
            this.AUserId = AUserId;
            this.AExtAuthCode = AExtAuthCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsduplicatedExtAuthCodeResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class IsduplicatedExtAuthCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public IsduplicatedExtAuthCodeResponse()
        {
        }
        
        public IsduplicatedExtAuthCodeResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWSPath", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UpdateWSPathRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AUserLogId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string AWSPath;
        
        public UpdateWSPathRequest()
        {
        }
        
        public UpdateWSPathRequest(int AUserLogId, string AWSPath)
        {
            this.AUserLogId = AUserLogId;
            this.AWSPath = AWSPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWSPathResponse", WrapperNamespace="urn:WsLoginIntf-IWsLogin", IsWrapped=true)]
    public partial class UpdateWSPathResponse
    {
        
        public UpdateWSPathResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWsLoginChannel : ServerLogin.IWsLogin, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WsLoginClient : System.ServiceModel.ClientBase<ServerLogin.IWsLogin>, ServerLogin.IWsLogin
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsLoginClient() : 
                base(WsLoginClient.GetDefaultBinding(), WsLoginClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IWsLoginPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsLoginClient(EndpointConfiguration endpointConfiguration) : 
                base(WsLoginClient.GetBindingForEndpoint(endpointConfiguration), WsLoginClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsLoginClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsLoginClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsLoginClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsLoginClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServerLogin.CheckModuleStationResponse CheckModuleStation(ServerLogin.CheckModuleStationRequest request)
        {
            return base.Channel.CheckModuleStation(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.CheckModuleStationResponse> CheckModuleStationAsync(ServerLogin.CheckModuleStationRequest request)
        {
            return base.Channel.CheckModuleStationAsync(request);
        }
        
        public ServerLogin.UserLoginResponse UserLogin(ServerLogin.UserLoginRequest request)
        {
            return base.Channel.UserLogin(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UserLoginResponse> UserLoginAsync(ServerLogin.UserLoginRequest request)
        {
            return base.Channel.UserLoginAsync(request);
        }
        
        public ServerLogin.UserLogin2Response UserLogin2(ServerLogin.UserLogin2Request request)
        {
            return base.Channel.UserLogin2(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UserLogin2Response> UserLogin2Async(ServerLogin.UserLogin2Request request)
        {
            return base.Channel.UserLogin2Async(request);
        }
        
        public ServerLogin.UserLogin3Response UserLogin3(ServerLogin.UserLogin3Request request)
        {
            return base.Channel.UserLogin3(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UserLogin3Response> UserLogin3Async(ServerLogin.UserLogin3Request request)
        {
            return base.Channel.UserLogin3Async(request);
        }
        
        public ServerLogin.UserLogin4Response UserLogin4(ServerLogin.UserLogin4Request request)
        {
            return base.Channel.UserLogin4(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UserLogin4Response> UserLogin4Async(ServerLogin.UserLogin4Request request)
        {
            return base.Channel.UserLogin4Async(request);
        }
        
        public ServerLogin.UserLogoutResponse UserLogout(ServerLogin.UserLogoutRequest request)
        {
            return base.Channel.UserLogout(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UserLogoutResponse> UserLogoutAsync(ServerLogin.UserLogoutRequest request)
        {
            return base.Channel.UserLogoutAsync(request);
        }
        
        public ServerLogin.UserLogoutForGateKeeperResponse UserLogoutForGateKeeper(ServerLogin.UserLogoutForGateKeeperRequest request)
        {
            return base.Channel.UserLogoutForGateKeeper(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UserLogoutForGateKeeperResponse> UserLogoutForGateKeeperAsync(ServerLogin.UserLogoutForGateKeeperRequest request)
        {
            return base.Channel.UserLogoutForGateKeeperAsync(request);
        }
        
        public ServerLogin.DisableUserResponse DisableUser(ServerLogin.DisableUserRequest request)
        {
            return base.Channel.DisableUser(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.DisableUserResponse> DisableUserAsync(ServerLogin.DisableUserRequest request)
        {
            return base.Channel.DisableUserAsync(request);
        }
        
        public ServerLogin.FindSessionItemDBResponse FindSessionItemDB(ServerLogin.FindSessionItemDBRequest request)
        {
            return base.Channel.FindSessionItemDB(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.FindSessionItemDBResponse> FindSessionItemDBAsync(ServerLogin.FindSessionItemDBRequest request)
        {
            return base.Channel.FindSessionItemDBAsync(request);
        }
        
        public ServerLogin.DeleteSessionDataResponse DeleteSessionData(ServerLogin.DeleteSessionDataRequest request)
        {
            return base.Channel.DeleteSessionData(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.DeleteSessionDataResponse> DeleteSessionDataAsync(ServerLogin.DeleteSessionDataRequest request)
        {
            return base.Channel.DeleteSessionDataAsync(request);
        }
        
        public ServerLogin.CreateUserLogDataResponse CreateUserLogData(ServerLogin.CreateUserLogDataRequest request)
        {
            return base.Channel.CreateUserLogData(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.CreateUserLogDataResponse> CreateUserLogDataAsync(ServerLogin.CreateUserLogDataRequest request)
        {
            return base.Channel.CreateUserLogDataAsync(request);
        }
        
        public ServerLogin.SynchUserLogDataResponse SynchUserLogData(ServerLogin.SynchUserLogDataRequest request)
        {
            return base.Channel.SynchUserLogData(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.SynchUserLogDataResponse> SynchUserLogDataAsync(ServerLogin.SynchUserLogDataRequest request)
        {
            return base.Channel.SynchUserLogDataAsync(request);
        }
        
        public ServerLogin.ChangeUserLoginResponse ChangeUserLogin(ServerLogin.ChangeUserLoginRequest request)
        {
            return base.Channel.ChangeUserLogin(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.ChangeUserLoginResponse> ChangeUserLoginAsync(ServerLogin.ChangeUserLoginRequest request)
        {
            return base.Channel.ChangeUserLoginAsync(request);
        }
        
        public ServerLogin.CheckResponse Check(ServerLogin.CheckRequest request)
        {
            return base.Channel.Check(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.CheckResponse> CheckAsync(ServerLogin.CheckRequest request)
        {
            return base.Channel.CheckAsync(request);
        }
        
        public ServerLogin.CheckSessionResponse CheckSession(ServerLogin.CheckSessionRequest request)
        {
            return base.Channel.CheckSession(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.CheckSessionResponse> CheckSessionAsync(ServerLogin.CheckSessionRequest request)
        {
            return base.Channel.CheckSessionAsync(request);
        }
        
        public ServerLogin.SetLoadTicketResponse SetLoadTicket(ServerLogin.SetLoadTicketRequest request)
        {
            return base.Channel.SetLoadTicket(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.SetLoadTicketResponse> SetLoadTicketAsync(ServerLogin.SetLoadTicketRequest request)
        {
            return base.Channel.SetLoadTicketAsync(request);
        }
        
        public ServerLogin.UpdateWorkstationVersionResponse UpdateWorkstationVersion(ServerLogin.UpdateWorkstationVersionRequest request)
        {
            return base.Channel.UpdateWorkstationVersion(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UpdateWorkstationVersionResponse> UpdateWorkstationVersionAsync(ServerLogin.UpdateWorkstationVersionRequest request)
        {
            return base.Channel.UpdateWorkstationVersionAsync(request);
        }
        
        public ServerLogin.RFID_CheckAntennaResponse RFID_CheckAntenna(ServerLogin.RFID_CheckAntennaRequest request)
        {
            return base.Channel.RFID_CheckAntenna(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.RFID_CheckAntennaResponse> RFID_CheckAntennaAsync(ServerLogin.RFID_CheckAntennaRequest request)
        {
            return base.Channel.RFID_CheckAntennaAsync(request);
        }
        
        public ServerLogin.RFID_CheckLoginResponse RFID_CheckLogin(ServerLogin.RFID_CheckLoginRequest request)
        {
            return base.Channel.RFID_CheckLogin(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.RFID_CheckLoginResponse> RFID_CheckLoginAsync(ServerLogin.RFID_CheckLoginRequest request)
        {
            return base.Channel.RFID_CheckLoginAsync(request);
        }
        
        public ServerLogin.ReCreateSessionResponse ReCreateSession(ServerLogin.ReCreateSessionRequest request)
        {
            return base.Channel.ReCreateSession(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.ReCreateSessionResponse> ReCreateSessionAsync(ServerLogin.ReCreateSessionRequest request)
        {
            return base.Channel.ReCreateSessionAsync(request);
        }
        
        public ServerLogin.IsDBCompatibleResponse IsDBCompatible(ServerLogin.IsDBCompatibleRequest request)
        {
            return base.Channel.IsDBCompatible(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.IsDBCompatibleResponse> IsDBCompatibleAsync(ServerLogin.IsDBCompatibleRequest request)
        {
            return base.Channel.IsDBCompatibleAsync(request);
        }
        
        public ServerLogin.GetWorkstationDeviceIdFromFamilyTypeResponse GetWorkstationDeviceIdFromFamilyType(ServerLogin.GetWorkstationDeviceIdFromFamilyTypeRequest request)
        {
            return base.Channel.GetWorkstationDeviceIdFromFamilyType(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.GetWorkstationDeviceIdFromFamilyTypeResponse> GetWorkstationDeviceIdFromFamilyTypeAsync(ServerLogin.GetWorkstationDeviceIdFromFamilyTypeRequest request)
        {
            return base.Channel.GetWorkstationDeviceIdFromFamilyTypeAsync(request);
        }
        
        public ServerLogin.ValidateChangeWorkstationResponse ValidateChangeWorkstation(ServerLogin.ValidateChangeWorkstationRequest request)
        {
            return base.Channel.ValidateChangeWorkstation(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.ValidateChangeWorkstationResponse> ValidateChangeWorkstationAsync(ServerLogin.ValidateChangeWorkstationRequest request)
        {
            return base.Channel.ValidateChangeWorkstationAsync(request);
        }
        
        public ServerLogin.IsduplicatedExtAuthCodeResponse IsduplicatedExtAuthCode(ServerLogin.IsduplicatedExtAuthCodeRequest request)
        {
            return base.Channel.IsduplicatedExtAuthCode(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.IsduplicatedExtAuthCodeResponse> IsduplicatedExtAuthCodeAsync(ServerLogin.IsduplicatedExtAuthCodeRequest request)
        {
            return base.Channel.IsduplicatedExtAuthCodeAsync(request);
        }
        
        public ServerLogin.UpdateWSPathResponse UpdateWSPath(ServerLogin.UpdateWSPathRequest request)
        {
            return base.Channel.UpdateWSPath(request);
        }
        
        public System.Threading.Tasks.Task<ServerLogin.UpdateWSPathResponse> UpdateWSPathAsync(ServerLogin.UpdateWSPathRequest request)
        {
            return base.Channel.UpdateWSPathAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWsLoginPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IWsLoginPort))
            {
                return new System.ServiceModel.EndpointAddress("https://bosdemo.enta.com.au/bosservices.dll/soap/IWsLogin");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsLoginClient.GetBindingForEndpoint(EndpointConfiguration.IWsLoginPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsLoginClient.GetEndpointAddress(EndpointConfiguration.IWsLoginPort);
        }
        
        public enum EndpointConfiguration
        {
            
            IWsLoginPort,
        }
    }
}
